Full support for Sends
ideoforms/AbletonOSC pull request #101
Opened 2023-09-09 16:04 UTC by steeltrack

Send support wasn't fully implemented (ex: no listeners). Fixed by aligning it with other mixer properties but adding some conditional logic to handle the additional sends index. The OSC endpoints also change from "send" to "sends" so they match the underlying Ableton property name like the other mixer properties.

2023-09-18 15:06 UTC, steeltrack commented
Added additional support for device parameters and a selected track listener.

2023-11-19 18:06 UTC, ideoforms requested changes
@steeltrack Thanks for the PR! And apologies for the slow reply, I've had a string of work commitments over the past few months and am just getting through the backlog...

New functionality looks good, and nice observation re `send` vs `sends` in the official Live naming.

Main thing missing is unit tests to verify the new functionality; see [CONTRIBUTING](https://github.com/ideoforms/AbletonOSC/blob/master/CONTRIBUTING.md) for details of running these. It would be great to have tests for:

 - set/get send values
 - listen for send
 - and ideally something for selected device/track listener (although I've not played much with the selected device functionality, so I don't know if these events can be triggered by automated actions)

Also added a couple of comments in-line.
Apologies for the conflict in README.md... the formatting of the table causes havoc for merging changes.

2023-11-19 18:06 UTC, ideoforms commented on abletonosc/device.py
> +        self.osc_server.add_handler("/live/device/get/parameter/value_string", create_device_callback(device_get_parameter_value_string))
Add some documentation about this function. I've not used Live's `str_for_value`; is this for human-readable representations of values, for UI etc?

2023-11-19 18:06 UTC, ideoforms commented on abletonosc/track.py
> +            # self._stop_mixer_listen(target, prop, params)
Delete commented line

2024-01-01 21:18 UTC, MartinSahlen commented
Is there a lot to do to get this merged? would love that!

2024-01-14 18:23 UTC, closed without merging

2024-01-14 23:38 UTC, steeltrack commented
I'll being submitting new PRs that are sync'd with latest master. I'm also going to be splitting this into two PRs.

2024-01-15 10:34 UTC, ideoforms commented
Thanks @steeltrack, much appreciated! I'll take a look as soon as the PRs are ready to go.